config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "recipes#index"

  # Defines the root path route ("/")
  resources :foods
  get '/general_shopping_list', to: 'general_shopping_list#index'
  resources :public_recipes, only: [:index]
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_food, dependent: :destroy
  has_many :food, through: :recipe_food

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { only_integer: true }
  validates :cooking_time, presence: true, numericality: { only_integer: true }
  validates :description, presence: true
  validates :user_id, presence: true

  def count_recipe_foods
    count = recipe_food.count
    sum_price = food.sum(:price)
    { count:, sum_price: }
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: %i[show destroy update]
  before_action :authenticate_user!

  def index
    @recipes = Recipe.includes(:user).where(user_id: current_user.id)
    puts "El usuario es #{current_user.id}"
  end

  def show
    unless @recipe.public || current_user == @recipe.user
      redirect_to root_path, alert: 'You cannot access it.'
      return
    end
    @recipe_foods = @recipe.recipe_food
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipe.new(recipe_params)
    puts "Recipe Parameters: #{recipe_params.inspect}"
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        puts @recipe.errors.full_messages
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    puts 'Receta eliminada correctamente' if @recipe.destroyed?
    redirect_to recipes_path
  end

  def update
    @recipe.toggle!(:public)
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def find_recipe
    @recipe = Recipe.find_by_id(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(
      :name,
      :preparation_time,
      :cooking_time,
      :description,
      :public,
      :user_id
    )
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<h1 class="d-flex justify-content-center">Recipes</h1>

<% @recipes.each do |recipe| %>
  <div class="card mb-3 d-flex justify-content-between border border-black p-2 m-3 recipes_head">
    <div class="card-header d-flex justify-content-between">
      <h2><%= link_to recipe.name, recipe %></h2>
      <div>
        <%= form_with(model: recipe, method: :delete, local: true) do |form| %>
          <%= form.submit 'Delete', class: 'btn btn-outline-danger' %>
        <% end %>
      </div>
    </div>
    <div class="recipe-description pt-3">
      <p><%= recipe.description %></p>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h1 class="container text-center"> Add a recipe </h1>
<div>
    <%= form_with(model: @recipe, method: :post) do |form|%>
        <div class="container d-flex flex-column">
            <%= form.label :name %>
            <%= form.text_field :name %>
            <%= form.label :preparation_time %>
            <%= form.number_field :preparation_time %>
            <%= form.label :cooking_time %>
            <%= form.number_field :cooking_time %>
            <%= form.label :description %>
            <%= form.text_area :description %>
            <%= form.hidden_field :public, value: false %>
            <%= form.hidden_field :user_id, value: current_user.id %>

            <%= form.submit %>
        </div>
    <% end %>
</div>

app/views/recipes/show.html.erb
<h2 class="d-flex justify-content-center"> <%= @recipe.name %> </h2>

<div class= "recipe-details-container d-flex justify-content-around">
    <div class= "recipe-details">
        <p>Preparation time:  <%= @recipe.preparation_time %> minutes</p>
        <p>Cooking time:  <%= @recipe.cooking_time %> minutes </p>
        <p>Description:  <%= @recipe.description %> </p>
    </div>
    <div class= "recipe-ingredients">
          <% if @recipe.public %>
            <%= button_to 'Public', recipe_path(@recipe), method: :put %>
          <% else %>
            <%= button_to 'Private', recipe_path(@recipe), method: :put %>
          <% end %>
    </div>
</div>

<div class="btn-option-container d-flex justify-content-around">
    <div class="d-flex">
    <%= link_to "Generate shopping list", general_shopping_list_path, class: "btn btn-primary" %>
    </div>

    <div class="d-flex">
    <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe), method: :get, class: "btn btn-primary" %>
    </div>
</div>



<div id="foods" class="m-5">
<table class="table table-striped rounded-table m-0">
    <thead>
    <tr>
        <th scope="col">
        <span>Food</span>
        <span><i class="fa fa-caret-up" aria-hidden="true"></i></span>
        </th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @recipe_foods.each do |recipe_food| %>
        <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %></td>
        <td>$<%= recipe_food.food.price %></td>
        <td>
        <div class="d-flex action_delete">
            <% if recipe_food.recipe.user_id == current_user.id%>
                <%= link_to "Edit this food", edit_food_path(recipe_food.food_id) %>&nbsp;|&nbsp;
                <%= button_to "Delete", [@recipe, recipe_food], method: :delete, class: "border border-0 text-decoration-underline text-primary" %>
            <% end %>
        </div>
        </td>
        </tr>
    <% end %>
    </tbody>
</table>
</div> 