config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "recipes#index"

  # Defines the root path route ("/")
  resources :foods
  get '/general_shopping_list', to: 'general_shopping_list#index'
  resources :public_recipes, only: [:index]
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :food_id, :recipe_id, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show destroy]

  def index
    @recipe_foods = RecipeFood.all
  end

  def show
    recipe_food = RecipeFood.find(params[:id])
    redirect_to recipe_path(recipe_food.recipe)
  end

  def new
    @user = current_user
    @recipe = Recipe.find(params[:recipe_id])
    @foods = @user.food
    @recipe_food = @recipe.recipe_food.build

    @ingredients = @foods.map { |food| ["#{food.name} in #{food.unit}", food.id] }
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_food.build(recipe_food_params)

    if @recipe_food.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.destroy
      flash[:notice] = 'Food was successfully deleted.'
    else
      flash[:alert] = 'Failed to delete food.'
    end
    redirect_to recipes_path, notice: 'Food was successfully deleted.'
  end

  private

  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/new.html.erb
<div class="form ff">
  <h2>Add new Ingredient</h2>
  <%= form_with(model: [@recipe, @recipe_food], url: recipe_recipe_foods_path(@recipe), local: true) do |form| %>
    <div class="input">
      <%= form.label :food_id %>
      <%= form.select :food_id, options_for_select(@ingredients), prompt: 'Pick ingredient...' %>
      <%= link_to "Add Food", new_food_path, method: :post, class: "btn btn-primary" %>
    </div>
    <div class="input">
      <%= form.label :quantity %>
      <%= form.text_field :quantity, placeholder: 'Enter quantity', required: true, class: 'form-input' %>
    </div>

    <%= form.submit "Create Ingredient", class: "submit" %>
  <% end %>
</div>