config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "recipes#index"

  # Defines the root path route ("/")
  resources :foods
  get '/general_shopping_list', to: 'general_shopping_list#index'
  resources :public_recipes, only: [:index]
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end
end

app/views/navigation/_navbar.html.erb
<ul class="nav nav-underline navbar-dark bg-dark">
  <div class="d-flex align-items-center">
    <%= link_to 'Recipe App', root_path, class:"navbar-brand" %>
  </div>

  <% if user_signed_in? %>
    <li class="nav-item">
      <%= form_with(url: destroy_user_session_path, method: :delete, local: false) do |form| %>
        <button type="submit" class="nav-link">Logout</button>
      <% end %>
    </li>
    <%# public recipes %>
    <li class="nav-item">
      <%= link_to "Public Recipes", public_recipes_path, class:"nav-link" %>
    </li>
    <%# my recipes %>
    <li class="nav-item">
      <%= link_to "My Recipes", recipes_path, method: :delete, class:"nav-link" %>
    </li>
    <%# add recipe %>
    <li class="nav-item">
        <%= link_to "New Recipe", new_recipe_path, method: :delete, class:"nav-link" %>
      </li>
    <%# foods %>
    <li class="nav-item">
      <%= link_to "Food", foods_path, class:"nav-link" %>
    </li>
    <%# add foods %>
    <li class="nav-item">
        <%= link_to "Add Food", new_food_path, class:"nav-link" %>
    </li>
      <% else %>
    <li class="nav-item">
      <%= link_to "Sign Up/In", new_user_session_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Public Recipes", public_recipes_path, class:"nav-link" %>
    </li>
  <% end %>
</ul>